# Server 配置
server:
  port: 8080                 # 服务监听端口
  mode: debug                # 运行模式，可选：debug（调试模式），release（生产模式），test（测试模式）
  read_timeout: 60          # 请求读取超时时间（单位：秒）
  write_timeout: 60         # 响应写入超时时间（单位：秒）
  idle_timeout: 60          # 连接空闲超时时间（单位：秒）
  session:
    secret: gin-skeleton    # Session 加密密钥，用于安全存储用户会话信息


# 数据库配置
database:
  driver: sqlite                 # 数据库驱动类型，可选值：mysql、sqlite
  dbname: runtime/skeleton.db # 数据库名或 SQLite 文件路径（若使用 mysql，需配置 host/port 等）

  # 以下为可选配置项，仅在使用 mysql 时生效
  # host: 127.0.0.1             # 数据库主机地址
  # port: 3306                  # 数据库端口（MySQL: 3306）
  # username: root              # 数据库用户名
  # password: secret            # 数据库密码
  # max_idle_conns: 10          # 最大空闲连接数（SQLite 可设为 0）
  # max_open_conns: 100         # 最大打开连接数（SQLite 可设为 0）
  # conn_max_lifetime: 300      # 单个连接最大生命周期（单位：秒，例如 300 = 5 分钟）

jwt:
  secret: "vosMykI4axI9IrUuI8JYxlaHnnEWLvfNrWE3gOwOBBk="


# 日志配置
logger:
  level: debug              # 日志级别，可选：debug, info, warn, error, fatal, panic
  path: runtime/log/app.log # 日志文件存储路径
  max_size: 100             # 单个日志文件最大大小（单位：MB）
  max_backups: 10           # 最多保留的旧日志文件数量
  max_age: 30               # 日志文件最大保存天数（单位：天）
  compress: true            # 是否启用日志压缩（启用后会将旧日志压缩为 .gz）
  format: json              # 日志格式，可选：json（结构化日志）、text（普通文本）

redis:
  addr: localhost:6379
  # password: 123456
  db: 2